version: "3.7"
services:
  redis:
    image: redis:6.2.5
    container_name: guardian_cache
    expose:
      - 6379
    networks:
      - guardian_network

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: guardian_app
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://cache
      - PORT=${PORT}
    ports:
      - ${LOCAL_PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./node_modules:/app/node_modules
      - ./.env:/app/.env
      - ./package.json:/app/package.json
    networks:
      - guardian_network

networks:
  guardian_network:
    driver: bridge
